# Generated by Django 4.1.1 on 2022-11-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SansaNews', '0002_imagenes_avisos_delete_carpetas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes_avisos',
            name='descripcion',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
